---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/ati/Asztal/IR-SZVK-07/ngonx_config
    ports:
      - :8080

    restart: unless-stopped